// List of Builderio routes for the App mobile
export enum SwitchRoutesBuilderioApp {
  Faq = "/faq",
  FourthSection = "/fourth-section",
  Home = "/home",
  HomeCampaing = "/home-campaing",
  HomeDetails = "/home-details",
  ThirdSection = "/third-section",
}

// List of routes for the Web
export enum SwitchRoutesWeb {
  Account = "/cuenta/mis-ahorros",
  AccountVoucherDetails = "/cuenta/mis-ahorros/cheque-ventajon/detalles/",
  AccountCashDiscountsDetails = "/cuenta/mis-ahorros/descuentos-efectivo/detalles/",
  AccountHelp = "/cuenta/mis-ahorros/como-funciona-descuentos-efectivo",
  AccountInsurances = "/cuenta/mis-seguros",
  AccountCardLink = "/cuenta/vincular-tarjeta",
  AccountCardRequest = "/cuenta/solicitar-tarjeta",
  AccountCardRequestInfo = "/cuenta/solicitar-tarjeta/informacion",
  AccountCardRequestSuccess = "/cuenta/solicitar-tarjeta/exito",
  AccountCardTransactions = "/cuenta/mis-movimientos",
  AccountCardTransactionsDetails = "/cuenta/mis-movimientos/detalles/",
  AccountNotifications = "/cuenta/mis-notificaciones",
  AccountUserDetail = "/cuenta/mis-datos",
  Addresses = "/direcciones",
  AppleCallback = "/callback/apple",
  ArcoRights = "/derechos-acceso",
  AssociatedCompanies = "/empresas-asociadas",
  AssociatedCompaniesDetails = "/empresas-asociadas/detalles/",
  AssociatedCompaniesMap = "/map-associated-companies",
  Cards = "/tarjeta",
  ConfirmationEmail = "/confirmation-email",
  Contact = "/contacto",
  Cookies = "/cookies",
  DataProtection = "/proteccion-datos",
  DataProtectionDelegate = "/delegado-proteccion-datos",
  EmailValidation = "/email-validation",
  ExternalLinkBlog = "https://www.ventajon.com/blog",
  ExternalLinkShop = "https://www.ventajon.com/tiendas-online",
  ExternalLinkShopDev = "https://webclubventajondesarrollo.ventajon.com/tiendas-online",
  ExternalLinkTravel = "https://www.viajerosventajon.com/",
  FacebookCallback = "/callback/facebook",
  FAQ = "/preguntas-frecuentes",
  GeneralConditions = "/condiciones-generales-contratacion",
  GeneralConditionsUseOfWeb = "/condiciones-generales-uso-web",
  GoogleCallback = "/callback/google",
  Home = "/",
  Insurances = "/seguros",
  InsurancesCalculator = "/seguros/seguros-salud-tasador",
  InsurancesDeath = "/seguros/seguros-decesos",
  InsurancesHealth = "/seguros/seguros-salud",
  InsurancesLife = "/seguros/seguros-vida",
  InsurancesPets = "/seguros/seguros-mascotas",
  InternalInformationChannel = "/canal-informacion-interno",
  LegalPolicy = "/politica-legal",
  Login = "/inciar-sesion",
  Magazine = "/revista",
  PasswordFormReset = "/cambiar-contrasena",
  PasswordRecovery = "/recuperar-contrasena",
  Promotions = "/promociones",
  Register = "/registro",
  RequestCard = "/solicitar-tarjeta-formulario",
  RequestCardInfo = "/solicitar-tarjeta-informacion",
  RequestCardSuccess = "/solicitar-tarjeta/exito",
  Travel = "/viajeros",
  Verify = "/verificacion",
  Verified = "/verificado",
  WorkWithUs = "/trabaja-con-nosotros",
}

// List of routes for the Admin Panel
export enum SwitchRoutesAdmin {
  AddNotification = "/admin/notificationes/anadir-notificacion",
  PasswordRecovery = "/admin/recuperar-contrasena",
  PasswordFormReset = "/admin/contrasena/restablecer",
  Categories = "/admin/categorias",
  CategoryDetails = "/admin/categorias/detalle",
  EditInsuranceRequest = "/admin/panel-de-seguros/editar-solicitud",
  EditNotification = "/admin/notificaciones/editar-notificacion",
  InsuranceDetail = "/admin/panel-de-seguros",
  InsurancePanel = "/admin/panel-de-seguros",
  Login = "/admin/iniciar-sesion",
  Notifications = "/admin/notificaciones",
  NotificationsDetails = "/admin/notificaciones",
}

// List of routes for the Companies panel
export enum SwitchRoutesCompanies {
  Contact = "/empresas/contacto",
  Home = "/empresas/home",
  Invoices = "/empresas/facturas",
  InvoiceDetails = "/empresas/facturas",
  Login = "/empresas/iniciar-sesion",
  Register = "/empresas/registro",
  RetrievePassword = "/empresas/recuperar-contrasena",
}

// This enum is to manually add new routes with market param
enum SwitchRoutesWithMarketParamAdditional {
  ArcoRights = SwitchRoutesWeb.ArcoRights,
  Cards = SwitchRoutesWeb.Cards,
  Cookies = SwitchRoutesWeb.Cookies,
  DataProtection = SwitchRoutesWeb.DataProtection,
  DataProtectionDelegate = SwitchRoutesWeb.DataProtectionDelegate,
  FAQ = SwitchRoutesWeb.FAQ,
  GeneralConditions = SwitchRoutesWeb.GeneralConditions,
  GeneralConditionsUseOfWeb = SwitchRoutesWeb.GeneralConditionsUseOfWeb,
  Home = SwitchRoutesWeb.Home,
  Insurances = SwitchRoutesWeb.Insurances,
  InsurancesDeath = SwitchRoutesWeb.InsurancesDeath,
  InsurancesHealth = SwitchRoutesWeb.InsurancesHealth,
  InsurancesLife = SwitchRoutesWeb.InsurancesLife,
  InsurancesPets = SwitchRoutesWeb.InsurancesPets,
  InternalInformationChannel = SwitchRoutesWeb.InternalInformationChannel,
  LegalPolicy = SwitchRoutesWeb.LegalPolicy,
  Magazine = SwitchRoutesWeb.Magazine,
  MapAssociatedCompanies = SwitchRoutesWeb.AssociatedCompaniesMap,
  Promotions = SwitchRoutesWeb.Promotions,
  Travel = SwitchRoutesWeb.Travel,
  WorkWithUs = SwitchRoutesWeb.WorkWithUs,
}

export const SwitchRoutesWithMarketParam = {
  ...SwitchRoutesBuilderioApp,
  ...SwitchRoutesWithMarketParamAdditional,
};